export const replacementCopy = {
  es: {
    detected: 'Formato detectado', unknown: 'No determinado', dimensions: 'Caja de texto', position: 'Posición de la línea base',
    empty: 'Dejá el campo vacío para eliminar este fragmento. No equivale a sanitizar el documento; para información sensible usá Tachar.',
    rotation: 'Rotación', opacity: 'Opacidad', spacing: 'Espaciado de letras / palabras', scale: 'Escala horizontal',
    metrics: 'Límites calculados con métricas de la fuente', estimated: 'Límites aproximados: el PDF no aporta métricas completas',
    layer: 'Capa declarada', layerUnknown: 'No identificada (no implica que no existan capas)',
    native: 'Conservar estructura PDF', raster: 'Reconstruir esta página', mode: 'Método de reemplazo',
    nativeNote: 'Edita el fragmento elegido con su fuente original. Conserva el resto del PDF y verifica que la fuente pueda escribir el texto nuevo. No convierte la página en imagen.',
    rasterNote: 'Convierte esta página en imagen y reconstruye el texto. Pierde enlaces, formularios y capas de esta página. El fondo elegido puede tapar elementos cercanos. Usá este modo sólo si aceptás esas pérdidas.',
    fit: 'Ajuste del texto nuevo', squeeze: 'Encajar en el ancho original', layout: 'Ancho natural; mantener lo que sigue', flow: 'Ancho natural; desplazar lo que sigue',
    fitNote: 'Encajar puede comprimir o estirar las letras. El ancho natural puede ocupar más espacio; revisá siempre la vista previa.',
    refusal: 'No se aplicó el cambio. No se puede garantizar este reemplazo conservando la estructura.',
    missing: 'La fuente original no contiene todos los caracteres solicitados.',
    ambiguous: 'No se pudo vincular este fragmento a un único objeto editable. Puede estar dividido, superpuesto o dentro de un objeto anidado.',
    different: 'El texto es demasiado diferente en longitud para encajarlo sin una deformación excesiva. Probá ancho natural o acortá el texto.',
    unsupported: 'El PDF usa una codificación u operación no compatible con la edición directa de este fragmento.',
    stale: 'El documento cambió. Volvé a seleccionar el fragmento.',
    font: 'Tipografía', noText: 'No se detectó texto seleccionable. Puede ser una imagen, trazados o una codificación ilegible. Probá Reconocer texto en Documento; OCR no recupera con certeza la tipografía original.',
    hidden: 'Texto invisible / capa OCR: el contenido visible puede estar en una imagen.',
    search: 'Filtrar fragmentos de esta página', fragments: 'Fragmentos detectados', colorUnknown: 'El color no pudo aislarse; el modo estructural lo conserva sin adivinarlo.',
  },
  en: {
    detected: 'Detected formatting', unknown: 'Unknown', dimensions: 'Text bounds', position: 'Baseline position',
    empty: 'Leave empty to remove this fragment. This is not document sanitization; use Redact for sensitive information.',
    rotation: 'Rotation', opacity: 'Opacity', spacing: 'Character / word spacing', scale: 'Horizontal scale',
    metrics: 'Bounds computed from font metrics', estimated: 'Estimated bounds: complete font metrics are unavailable',
    layer: 'Declared layer', layerUnknown: 'Not identified (does not mean there are no layers)',
    native: 'Preserve PDF structure', raster: 'Rebuild this page', mode: 'Replacement method',
    nativeNote: 'Edits the selected fragment with its original font. Preserves the rest of the PDF and checks whether the font can encode the new text. Does not turn the page into an image.',
    rasterNote: 'Turns this page into an image and rebuilds its text. Links, forms and layers on this page are lost. The chosen background may cover nearby elements. Use only if you accept these losses.',
    fit: 'New text fitting', squeeze: 'Fit original width', layout: 'Natural width; keep following text fixed', flow: 'Natural width; move following text',
    fitNote: 'Fitting can stretch or compress glyphs. Natural width can occupy more space; always inspect the preview.',
    refusal: 'No change was applied. This replacement cannot be guaranteed while preserving structure.',
    missing: 'The original font does not contain all requested characters.',
    ambiguous: 'This fragment could not be mapped to a unique editable object. It may be split, overlapping or nested.',
    different: 'The text length is too different to fit without excessive distortion. Try natural width or shorter text.',
    unsupported: 'The PDF uses an encoding or operation unsupported by direct editing of this fragment.',
    stale: 'The document changed. Select the fragment again.',
    font: 'Typeface', noText: 'No selectable text was detected. This may be an image, outlines or unreadable encoding. Try Recognize text in Document; OCR cannot reliably recover the original typeface.',
    hidden: 'Invisible text / OCR layer: visible content may be an image.',
    search: 'Filter fragments on this page', fragments: 'Detected fragments', colorUnknown: 'The color could not be isolated; structural mode preserves it without guessing.',
  },
};
