export const accountCopy = {
  es: {
    title: 'Mi cuenta', intro: 'Tus proveedores de IA, disponibles cuando entrás con tu cuenta.',
    login: 'Entrar', signup: 'Crear cuenta', logout: 'Cerrar sesión',
    welcome: 'Creá tu cuenta con un correo y una contraseña. Si usás Gmail, ingresá esa dirección como correo.',
    privacy: 'Cada cuenta usa sus propias claves y paga el consumo a su proveedor de IA. Guardamos las claves cifradas y sólo mostramos sus últimos cuatro caracteres. Los PDF y el OCR siguen procesándose en tu navegador; esta cuenta no guarda documentos.',
    providers: 'Mis proveedores', empty: 'Todavía no guardaste ningún proveedor.',
    label: 'Nombre para reconocerlo', provider: 'Proveedor', model: 'Modelo', endpoint: 'URL base compatible', key: 'Clave API',
    save: 'Guardar proveedor', remove: 'Eliminar', saved: 'Proveedor guardado. Ya podés elegirlo al traducir.',
    removed: 'Proveedor eliminado.', translate: 'Ir a traducir PDF', loading: 'Cargando tu cuenta…', retry: 'Reintentar',
    unavailable: 'No pudimos cargar tu cuenta. Reintentá en unos momentos.',
    notConfigured: 'El acceso a cuentas todavía no está habilitado en esta instalación.',
    session: 'Tu sesión venció. Volvé a entrar para continuar.',
    invalid: 'Revisá el nombre, el modelo y la clave. Las URL compatibles deben estar habilitadas en OpenPDF.',
    limit: 'Podés guardar hasta 10 proveedores. Eliminá uno para agregar otro.',
    select: 'Clave para esta traducción', temporary: 'Ingresar una clave sólo para esta sesión',
    connect: 'Entrá a Mi cuenta para guardar y reutilizar tus proveedores.',
    manage: 'Administrar mis proveedores', using: 'Usando tu proveedor guardado',
    billing: 'Guardar una clave no confirma que tenga saldo ni que el modelo esté disponible. El proveedor cobra las solicitudes que hagas.',
  },
  en: {
    title: 'My account', intro: 'Your AI providers, available whenever you sign in.',
    login: 'Sign in', signup: 'Create account', logout: 'Sign out',
    welcome: 'Create an account with an email and password. You can use your Gmail address as the email.',
    privacy: 'Each account uses its own keys and pays its AI provider for usage. Keys are stored encrypted; only their last four characters are displayed. PDFs and OCR are still processed in your browser; this account does not store documents.',
    providers: 'My providers', empty: 'You have not saved any providers yet.',
    label: 'Name to recognize it', provider: 'Provider', model: 'Model', endpoint: 'Compatible base URL', key: 'API key',
    save: 'Save provider', remove: 'Delete', saved: 'Provider saved. You can now select it when translating.',
    removed: 'Provider deleted.', translate: 'Translate a PDF', loading: 'Loading your account…', retry: 'Retry',
    unavailable: 'Your account could not be loaded. Please try again shortly.',
    notConfigured: 'Accounts are not enabled in this installation yet.',
    session: 'Your session expired. Sign in again to continue.',
    invalid: 'Check the name, model and key. Compatible URLs must be enabled in OpenPDF.',
    limit: 'You can save up to 10 providers. Delete one to add another.',
    select: 'Key for this translation', temporary: 'Enter a key for this session only',
    connect: 'Sign in to My account to save and reuse your providers.',
    manage: 'Manage my providers', using: 'Using your saved provider',
    billing: 'Saving a key does not confirm its balance or model availability. Your provider charges for requests you make.',
  },
} as const;
